name: tab_settle
description: "A new Flutter project initialized with custom starter architecture."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Logging
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1

  # State Management & Routing
  go_router: ^17.0.1
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_hooks: ^0.21.0

  # Code Generation Annotations
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Utilities & Networking
  cupertino_icons: ^1.0.8
  http: ^1.6.0

  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.1
  intl: ^0.20.3
  image: ^4.9.1
  image_picker: ^1.2.3
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0

  faker: ^2.2.0
  shared_preferences: ^2.5.5
  qr_bar_code: ^4.0.0
  share_plus: ^13.3.0
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  async: ^2.13.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3

  # Code Generators
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/test_receipts/
    - assets/graphics/
    - .env

#  dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/graphics/splash-logo.png
  color: "#121212"
  android: true
  ios: true
  web: true
  web_image_mode: center
  android_12:
    color: "#121212"
    image: assets/graphics/splash-logo.png

