// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbciRb5tWQAsN50eoaPaC0tPU2Z0VLpbw',
    appId: '1:566341541330:web:a3eb03f4558e266be47c0b',
    messagingSenderId: '566341541330',
    projectId: 'bill-share-mcdona22',
    authDomain: 'bill-share-mcdona22.firebaseapp.com',
    storageBucket: 'bill-share-mcdona22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHgVJwYHdJFCrMQx-DeiG5TrFpJfsS24',
    appId: '1:566341541330:android:ffa5478d33aa7797e47c0b',
    messagingSenderId: '566341541330',
    projectId: 'bill-share-mcdona22',
    storageBucket: 'bill-share-mcdona22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwx8V04edYt7FAxH8o_UF3OMcKuIQ84-Q',
    appId: '1:566341541330:ios:94cb1184e87d14cfe47c0b',
    messagingSenderId: '566341541330',
    projectId: 'bill-share-mcdona22',
    storageBucket: 'bill-share-mcdona22.firebasestorage.app',
    iosBundleId: 'com.mcdona22.tabsettle.tabSettle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwx8V04edYt7FAxH8o_UF3OMcKuIQ84-Q',
    appId: '1:566341541330:ios:94cb1184e87d14cfe47c0b',
    messagingSenderId: '566341541330',
    projectId: 'bill-share-mcdona22',
    storageBucket: 'bill-share-mcdona22.firebasestorage.app',
    iosBundleId: 'com.mcdona22.tabsettle.tabSettle',
  );
}
